import { escapeHtml } from "@/lib/validation";
import type { CeremonyPosition } from "./_types";

/**
 * Opens a print window with the ceremony layout — left side, center altar,
 * right side, processional order. Pure: takes positions and renders, no
 * dependency on component state.
 */
export function printCeremony(ceremonyPositions: CeremonyPosition[]): void {
  const leftSide = ceremonyPositions.filter((p) => p.side === "left");
  const rightSide = ceremonyPositions.filter((p) => p.side === "right");
  const centerPositions = ceremonyPositions.filter((p) => p.side === "center");

  const printWin = window.open("", "_blank");
  if (!printWin) return;
  const esc = escapeHtml;

  const centerHtml = centerPositions
    .map(
      (p) =>
        `<div style="font-size:18px;font-weight:600;color:#1A1A2E;margin:6px 0">${esc(p.person_name)} <span style="font-size:13px;color:#8E7A9E;font-weight:400">${esc(p.role || "")}</span></div>`
    )
    .join("");

  const sideHtml = (positions: CeremonyPosition[]) =>
    positions.length === 0
      ? '<p style="color:#8E7A9E;font-size:14px;text-align:center;padding:16px 0">—</p>'
      : positions
          .sort((a, b) => a.position_order - b.position_order)
          .map(
            (p, i) =>
              `<div style="display:flex;align-items:center;gap:8px;padding:6px 12px;border-bottom:1px solid #E8D5B7"><span style="color:#8E7A9E;font-size:13px;width:20px">${i + 1}</span><span style="font-size:15px;color:#1A1A2E;flex:1">${esc(p.person_name)}</span><span style="font-size:12px;color:#8E7A9E">${esc(p.role || "")}</span></div>`
          )
          .join("");

  printWin.document.write(`<!DOCTYPE html><html><head><title>Ceremony Layout</title><style>body{font-family:system-ui,sans-serif;padding:40px;color:#1A1A2E}@media print{body{padding:20px}}</style></head><body>
    <h1 style="font-size:24px;margin-bottom:4px">Ceremony Layout</h1>
    <p style="color:#8E7A9E;font-size:13px;margin-bottom:32px">Processional order: #1 walks first</p>
    <div style="text-align:center;background:#EDE7DF;border-radius:12px;padding:24px;margin-bottom:32px">
      <p style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#8E7A9E;font-weight:600">Altar</p>
      ${centerHtml}
    </div>
    <div style="display:grid;grid-template-columns:1fr 40px 1fr;gap:0;max-width:700px;margin:0 auto">
      <div><h3 style="text-align:center;font-size:14px;color:#8E7A9E;margin-bottom:12px">Left Side</h3>${sideHtml(leftSide)}</div>
      <div style="display:flex;align-items:stretch;justify-content:center"><div style="width:2px;background:linear-gradient(to bottom,#E8D5B7,#D4A5A5);border-radius:1px"></div></div>
      <div><h3 style="text-align:center;font-size:14px;color:#8E7A9E;margin-bottom:12px">Right Side</h3>${sideHtml(rightSide)}</div>
    </div>
    <div style="text-align:center;margin-top:40px"><div style="display:inline-block;background:#FAF8FC;border-radius:999px;padding:8px 24px;border:1px solid #E8D5B7"><p style="font-size:13px;color:#8E7A9E">Guest Seating</p></div></div>
    <p style="text-align:center;color:#8E7A9E;font-size:11px;margin-top:32px">Generated by eydn.app</p>
  </body></html>`);
  printWin.document.close();
  printWin.print();
}
